// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
	"github.com/ajjensen13/gke"
	"net"
	"net/http"
)

// Injectors from rproxy_wireinject.go:

func newListener(ctx context.Context, l gke.Logger) (net.Listener, func(), error) {
	config := provideConfig(l)
	storageClient, cleanup, err := gke.NewStorageClient(ctx)
	if err != nil {
		return nil, nil, err
	}
	bucketHandle := provideBucketHandle(l, config, storageClient)
	cache := provideAutocertCache(l, bucketHandle)
	v := provideDomains(l, config)
	listener := provideListener(l, cache, v)
	return listener, func() {
		cleanup()
	}, nil
}

func newServer(ctx context.Context, l gke.Logger) (*http.Server, func(), error) {
	config := provideConfig(l)
	handler := provideHandler(l, config)
	server, err := gke.NewServer(ctx, handler, l)
	if err != nil {
		return nil, nil, err
	}
	return server, func() {
	}, nil
}
