{{ range .Values.config.projectedSources -}}
{{ if .configMapName -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .configMapName }}
data:
  {{ range .configMapData -}}
  {{ .name }}: |
    {{ with .jsonData -}}{{ . | toJson }}{{- end }}
  {{- end }}
{{- end }}
{{- end }}