apiVersion: v1
kind: Service
metadata:
  name: {{ include "rproxy.name" . }}-svc
  labels:
    {{- include "rproxy.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: {{ .Values.service.name }}
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: proxy
  selector:
    {{- include "rproxy.selectorLabels" . | nindent 4 }}
